apiVersion: v1
kind: ConfigMap
metadata:
  name: inventrack-config
  namespace: inventrack-prod
data:
  PORT: "4000"
  DB_HOST: mysql
  DB_USER: root
  DB_NAME: inventrack
  MYSQL_DATABASE: inventrack
