apiVersion: v1
kind: Secret
metadata:
  name: inventrack-secret
  namespace: inventrack-prod
type: Opaque
stringData:
  DB_PASSWORD: CAMBIAR_PASSWORD_MYSQL
  JWT_SECRET: CAMBIAR_JWT_SECRET_LARGO
  GROQ_API_KEY: CAMBIAR_GROQ_API_KEY
